feat: support get branch info & support auto rerun when internal code changed

diff --git a/.github/workflows/CI-request-trigger.yml b/.github/workflows/CI-request-trigger.yml
--- a/.github/workflows/CI-request-trigger.yml
+++ b/.github/workflows/CI-request-trigger.yml
@@ -31,7 +31,7 @@ jobs:
 
       # Runs trigger CI
       - name: Make the script files executable
-        run: chmod +x trigger-CI.sh get-CI-result.sh
+        run: chmod +x trigger-CI.sh get-CI-result.sh get-branch-info.sh
       - name: trigger a CI
         run: |
           COMMIT_ID=$([ "${{ github.event_name }}" == "pull_request" ] && echo "${{ github.event.pull_request.head.sha }}" || echo "${{ github.sha }}")
@@ -40,7 +40,39 @@ jobs:
           PR_ID=$(echo "$GITHUB_REF" | sed 's@refs/pull/\([0-9]\+\)/.*@\1@')
           echo "PR ID is $PR_ID"
           ./trigger-CI.sh "$COMMIT_ID" "${{ secrets.CI_SECRET }}" "${{ github.event.pull_request.head.repo.clone_url }}" "$PR_ID"
-
+      - name: Add comment via REST API
+        continue-on-error: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          set +e
+          PR_ID=${{ github.event.pull_request.number }}
+          BRANCH_NAME="open_merge/${PR_ID}"
+          echo "BRANCH_NAME is $BRANCH_NAME"
+          CURRENT_INTERNAL_COMMITID="UNKNOWN"
+          echo "current internal commit id is $CURRENT_INTERNAL_COMMITID"
+          BRANCH_INFO=$(sh ./get-branch-info.sh "${BRANCH_NAME}")
+          if [ $? -eq 0 ]; then
+              echo "get branch info : $BRANCH_INFO"
+              CURRENT_INTERNAL_COMMITID=$(echo "$BRANCH_INFO" | jq -r '.commit.id')
+              echo "$CURRENT_INTERNAL_COMMITID"
+          else
+              echo "Error: Failed to query CI status ${BRANCH_INFO} pass add comment"
+              exit 0
+          fi
+          echo "current internal commit id is $CURRENT_INTERNAL_COMMITID"
+          MAIN_BRANCH_INFO=$(./get-branch-info.sh "main-internal")
+          if [ $? -eq 0 ]; then
+              MAIN_INTERNAL_COMMITID=$(echo "$MAIN_BRANCH_INFO" | jq -r '.commit.id')
+              if [ "${CURRENT_INTERNAL_COMMITID}" != "${MAIN_INTERNAL_COMMITID}" ]; then
+                  curl -X POST https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
+                        -H "Authorization: Bearer $GITHUB_TOKEN" \
+                        -H "Accept: application/vnd.github.v3+json" \
+                        -d '{
+                            "body": "internal source has been updated, please review the changes!"
+                        }'
+              fi
+          fi
       # Runs get CI result
       - name: Get CI result
         run: |
